### ISSUE TITLE
TFA FAQ

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#44]
As a company, we should put together FAQ entries for TFA before hard launch. 

@ezra-latina can you please start a doc for this and link here, adding the most frequently asked Qs that come up during your onboarding sessions.

**Comment by hannahdonovan** [comment]
@ezra-latina can you please link up the beginnings of the FAQ doc? We'll need this complete by Fri 4/24 so that we have enough time to link it up on our website trash.app as well as the TFA site.

Q. where do you think is best to link this on the TFA site?

**Comment by ezra-latina** [comment]
Here is a link to the doc - still need to fill it out some more

A: I think it would be best to add another page/link below Community Videos in the sidebar that says "Terms"

**Comment by ezra-latina** [comment]
I don't have the right permissions to update the status of this? But anyway, I finished writing this up :)

**Comment by hannahdonovan** [comment]
Can you create a Benny ticket for the terms and tag it w SB? I would recommend making it a nav update ticket and also mention we should change videos to your videos, I think this is currently a bit confusing

**Comment by hannahdonovan** [comment]
@ezra-latina please add the copy blurb to this ticket for the brothers when you have it. Thank you!

**Comment by hannahdonovan** [comment]
https://drive.google.com/drive/u/0/folders/11VANw6iT68FYl_FdJNpXr6RytnBzaDK4

**Comment by TrevorBaum** [comment]
@hannahdonovan Will the TFA FAQ page be part of the TRASH homepage, not part of the TFA site? From the meeting today it seemed like we'd be adding this to the TRASH hp but the comments above seem like it should be part of the TFA site, which I would think SB would have to add?

Will that create any confusion nav-wise? Should I change the "Home" link at the top of the TFA FAQ to go back to the TFA site, and not the TRASH site?

**Comment by ezra-latina** [comment]
Copy:

FAQ 🤔

Do I need to allow other users to use my tracks on TRASH?
Yes, for now all tracks posted to TRASH are made publicly available. However, you still have full control to remove your tracks from TRASH at any time, and there will be no new uses of your songs.

How will my music be credited in TRASH?
Your music will be available in the Featured Music section of the Sound tab under your artist name. Anytime it is chosen as the soundtrack for a video, your track’s info will be displayed in the top-left corner under the account’s username in this format: “Your Artist Name - Your Track Name”.

Will I be compensated for posting my music on TRASH?
No, we do not currently offer compensation for tracks uploaded for use on TRASH. The value for artists lies in the great videos you will be able to make for free, not to mention the new fans who discover your tracks when our AI picks them to soundtrack their videos.

My friend helped me create this track and I have their permission to upload it, should I select “I have co-creators” or “All me”?
If you have permission from your co-creators then you can select “All me”. If you don’t have permission, make sure to get that first!

I have a record or publishing deal - why can’t I upload my tracks to TRASH?
Because of licensing restrictions, we are unable to accept tracks that are associated with a recording or publishing deal. If you are able to get permission from all other parties, reach out to us at artists@trash.app, and we can help you post your tracks.

I did a great cover version of another artist’s song - can I upload that to TRASH?
Probably not. Artists must own all song rights including master and publishing in order to upload them to TRASH. If you do have permission from the artist you covered, reach out to us at artists@trash.app, and we can help you post your tracks.

Why won’t my track info save?
A common cause of this problem is not having your profile information filled out before uploading a track. Make sure to set your Artist Name and Username in your profile before attempting an upload. If this doesn’t fix the problem, please reach out to us at artists@trash.app.

I can’t upload my song file, what should I do?
Is your song file too large? Make sure it is less than 60MB. Certain file types like .wav files are very large. You can make these files smaller by converting them to MP3 format. An easy way to do this is to drag them into iTunes → click File → Convert → Create MP3 version. 

How can I find my music in TRASH after uploading?
Find your music in TRASH in the SOUND tab when creating a new video. Scroll down to Featured Music and find your music under your Artist Name. It’s alphabetical!

Why can’t I see my track in TRASH?
Most likely, this is because the track was not Published. If you go to Tracks on the TRASH for Artists website, you can check the status of your track. If it says Draft, you will need to click on the three-dot icon to edit the track. Go to step 3 and select the rainbow Publish button.

How can I make a longer video?
Select the Music Video style at the bottom of the screen when editing your video to make a full-length music video. 

Can I choose a specific part of the song?
Unfortunately, this feature is not available yet. We are hoping to add this soon!

How can I take my tracks down?
Go to Tracks on the TRASH for Artists website. Click the three-dot icon next to the track you want to delete and select Delete. 

Can I remove the TRASH watermark from my video?
No, you cannot remove the watermark. This is our attribution for helping with editing your video. But we are open to feedback about how to make this better. Reach out to feedback@trash.app!

I just shared my video on TRASH, where is it?
You can find your video in the NEW channel if it has just been posted. You can also view your videos on your profile. See if you can make it to the GOAT (Greatest of All TRASH) channel!

Can I see the videos made with my music?
Yes! If you go to the Community Videos page on the TRASH for Artists website, you will see all of the videos that have been made with your tracks!

**Comment by TrevorBaum** [comment]
The [TFA FAQ](https://trash.app/FAQ-Artists) page is now live. It's not linked up to the main site yet, but I will do that as we get closer to launch. Feel free to have a look and QA.

**Comment by ezra-latina** [comment]
@TrevorBaum from our sync:
- update email contact from feedback@ to artists@
- update all instances of music@ to artists@
