### ISSUE TITLE
Add footer (or sidebar) to TFA site

### ISSUE THREAD

**Issue by hannahdonovan** [TRASH-INC/trash-inc.github.io#51]
Needs links to:

Primary:HELP & FAQ (artist version, not what is on the main site)COMMUNITY RULES (same as main site, we're changing z to s)MAIN SITE

Secondary:PRIVACY (same as main site)TERMS (same as main site, but will updated with new copy)DMCA (same as main site)©TRASH INC.

and also do this things:

logo on interior should be updated to reflect the one on the homepage

copy on logged in homepage should be shortened

update footer to be on the logged in version of the site too

remove 2 panels at bottom (as part of the footer update)

https://www.figma.com/file/9CqCAYga75Y1ESNZ7iPdXs/TRASH-for-Artists_SB?node-id=0%3A1

**Comment by piotr-brzeczek-sb** [comment]
https://kmpgroup.atlassian.net/browse/TRSH-277

**Comment by drewolbrich** [comment]
Note: The TRASH iOS app strongly relies on the URL https://www.trash.app/communityrulez (with a Z) so if you change the text "Community Rulez" to "Community Rules" throughout the web site, then if you happen to also change the spelling of this URL to https://www.trash.app/communityrules (with an S), the app will break. (It will display a 404 error instead of the community rules, which will be a bad user experience.)

If you do feel compelled to change the spelling of the URL, please make the old URL https://www.trash.app/communityrulez redirect to the new URL with the new spelling.

**Comment by karina4now** [comment]
> Drew commented in Jira:

Note: The TRASH iOS app strongly relies on the URLhttps://www.trash.app/communityrulez(with a Z) so if you change the text "Community Rulez" to "Community Rules" throughout the web site, then if you happen to also change the spelling of this URL tohttps://www.trash.app/communityrules(with an S), the app will break. (It will display a 404 error instead of the community rules, which will be a bad user experience.)

If you do feel compelled to change the spelling of the URL, please make the old URLhttps://www.trash.app/communityrulezredirect to the new URL with the new spelling.

**Comment by TrevorBaum** [comment]
Feedback for the footer below:

Homepage footer (logged out):
- Change "ARTIST CONTACT & FAQ" text to "HELP & FAQ" - this should link to https://trash.app/FAQ-Artists
- Change "TRASH.APP" text to "MAIN SITE"

Homepage footer (logged in):
- Change "Faq" text to "HELP & FAQ" - this should link to https://trash.app/FAQ-Artists
- Add "MAIN SITE" link under HELP & FAQ link, which should link to trash.app

**Comment by karina4now** [comment]
> Wojciech Krysiak commented in Jira:

Arkadiusz Pęcherzalong with this task I also update the empty states for all elements in the sidebar according to the design.

**Comment by karina4now** [comment]
> Arkadiusz Pęcherz commented in Jira:

Logged out page footer is not adjusted according to comments. I checked on benny-banana where logged-in footer looks like partially done, but without proper texts


```
Homepage footer (logged out):

Change "ARTIST CONTACT & FAQ" text to "HELP & FAQ" - this should link to https://trash.app/FAQ-Artists
Change "TRASH.APP" text to "MAIN SITE"
```

[file id="f626654d-ab26-45ac-8858-9dfee8196403"]

**Comment by karina4now** [comment]
> Wojciech Krysiak commented in Jira:

Arkadiusz Pęcherzafter discussing this withHan Donovanwe decided to push it as it is today

**Comment by chihyuC** [comment]
dup of https://github.com/TRASH-INC/Benny/issues/740
